index.js, js.js, package.json, ts.js
- uses standard-with-typescript for .ts files
- adds eslint-plugin-etc to be able to use `etc/prefer-interface`
- [https://ncjamieson.com/prefer-interfaces/](https://ncjamieson.com/prefer-interfaces/)
- more rules from this package can be enabled in the future
- lints repo files
- updates deps
- standard from 14 to 16 (and deps)
- eslint from 6 to 7
- removes unchanged rules from standard
- dot-notation
- no-case-declarations
- no-constant-condition
- no-empty-pattern
- no-labels
- quote-props
- removes rule `require-await`
- changes rules `jsdoc/no-undefined-types` from warn to off
- changes rule `jsdoc/require-param-description` from warn to off
- changes rule `jsdoc/valid-types` from warn to off
- change eslint rule values from numbers to 'off', 'warn' and 'error' its just easier to …
=> feat: add standard ts config and clean up

js.js
Setting the value to `false` means it is not writable
=> fix: use eslint env instead of individual globals

package-lock.json, package.json
- this makes ts standard aligned with normal standard
- jsdoc new version is a major
BREAKING CHANGE: jsdocs rules were updates and may breaking the linter.
=> feat: update ts standard linter and jsdocs

.github/dependabot.yml, .gitignore, package-lock.json, package.json
A new `eslint-config-standard-with-typescript` has been released which causes `eslint-plugin-etc` to not get hoisted and breaks linting everywhere.
The breaking change in `eslint-config-standard-with-typescript` appears to be dep updates that we were using anyway.
=> chore: update deps

ts.js
Disable the default rules that require return types and jsdoc `@param`
annotations as the compiler can figure these out.
May need re-enabling if it compromises doc generation.
=> feat: make ts less verbose

ts.js
Allow aliasing self for use within (async) generator functions.
Fixes: #104
=> fix: allow self-aliases

ts.js
When the compiler can derive return types, it often creates Franken-types of all the properties of a returned type instead of using an interface.
Worse, when it detects an interface it often imports it from a filesystem path instead of an exports map path (e.g. `module/dist/src/foo.js` instead of `module/foo`) which then breaks downstream consumers.
Instead, let's require return types to be explicit to catch these things early.
=> feat!: require explicit return types

ts.js
~~add promise related lint rules~~
=> feat: disallow awaiting non thenable values

ts.js
Sometimes we don't know the type of a thing but it's ok to turn it into a string.
=> fix: allow stringifying any

js.js
Allow using the `continue` statement in loops.  The warning this generates is usually spurious and often ignored.
=> fix: allow continue in loops

js.js, ts.js
Lint import sorting, and support auto-fixing of import order. see https://github.com/ipfs/aegir/pull/1178 for an example
=> feat!: add import sorting rule

index.js
Add `*.jsx` and `*.tsx` to list of files that are linted.
BREAKING CHANGE: previously jsx and tsx files were not linted, now they are
=> feat!: lint jsx

ts.js
Returning unawaited promises from inside try/catch blocks is usually a bug as the author more than likely intends the catch part to handle errors.
The configuration in this PR disallows `await` before `return` unless it is inside a `try/catch` in which case it is required.
`await` before `return` doesn't cause any harm but I don't think we can configure the rule any other way.
This is a breaking change but one that is fixable with `npm run lint -- --fix`
Fixes: #130
BREAKING CHANGE: `await` is not allowed before `return` unless it is inside a `try/catch` in which case it is required
=> fix!: only require `await`ing promises returned from inside try/catch blocks

src/js.js
The import ordering is closer to our internal conventions like this, so this change becomes less disruptive.
=> fix: remove import newlines and specify all groups

package.json
Requires an aegir update for the build to pass, since aegir depends on this module and the dependency resolution alogrithm results in config that is incompatible with the resolved eslint-plugin-jsdoc dep version.
=> chore: restore linting

src/ts.js
- Enforce this rule https://typescript-eslint.io/rules/method-signature-style#method
This is important for generated docs, which distinguish between methods and properties.  Without this rule, functions on an interface/object can appear as properties rather than methods:
I tested this rule against the js-libp2p monorepo, and using this rule results in API docs that now properly distinguish between methods and properties.
BREAKING CHANGE: All interfaces now need to use method signature style rather than property function style
eg:
before
```ts
interface Foo {
bar: (baz: number) => void
}
```
after
```ts
interface Foo {
bar(baz: number): void
}
```
=> feat!: add method-signature-style rule

src/ts.js
- See https://github.com/ipfs/aegir/issues/1459
Aegir currently relies on typescript to perform two linter rules, which is annoying for reasons mentioned in the above issue.
- `noFallthroughCasesInSwitch`
- `noUnusedLocals`
This PR makes typescript rules more strict to enforce both of these conditions.
For `noFallthroughCasesInSwitch`, it appears that the `standard` eslint rule set [already includes](https://github.com/standard/eslint-config-standard/blob/master/src/index.ts#L143) the [`no-fallthrough`](https://eslint.org/docs/latest/rules/no-fallthrough) rule.
So this PR only needs to enforce `noUnusedLocal`, and we just add [`@typescript-eslint/no-unused-vars`](https://typescript-eslint.io/rules/no-unused-vars/).
=> fix: use @typescript-eslint/no-unused-vars

src/ts.js
`tsc` already handles erroring on undefined variables so the check does nothing.
Worse, as of `v4` of `typescript-eslint` third party types are now treated as undefined by eslint so cause spurious errors.
`typescript-eslint` [recommends disabling it](https://typescript-eslint.io/troubleshooting/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors).
=> fix: turn off no-undef for ts files

src/ts.js
Disables two rules:
`@typescript-eslint/no-unsafe-argument` - this prevents passing vars with an `any` type to functions.
Unfortunately we still deal with untyped modules so this will happen.
`@typescript-eslint/unbound-method` - this prevents referencing functions without invoking them.
We need to disable this to do things like pass functions passed as part of an options object on to other functions.
=> fix: allow `any` args and referencing functions by property name

package.json
The latest `eslint-plugin-jsdoc` broke rule resolution, pin until https://github.com/gajus/eslint-plugin-jsdoc/issues/1277 is fixed.
=> fix: pin eslint-plugin-jsdoc
